import {
  LayoutDashboard,
  ShoppingCart,
  Receipt,
  Package,
  Boxes,
  Smartphone,
  Users,
  CalendarClock,
  Truck,
  ShoppingBag,
  Wallet,
  Coins,
  Repeat,
  UserCheck,
  Banknote,
  Zap,
  BarChart3,
  Bell,
  ShieldCheck,
  History,
  Settings,
} from 'lucide-react';
import { NavigationItem } from '../types';

export const NAVIGATION_CATEGORIES = [
  { id: 'core', label: 'الرئيسية', labelFr: 'Principal', labelEn: 'Main' },
  { id: 'operations', label: 'المبيعات والخدمات', labelFr: 'Ventes & Services', labelEn: 'Sales & Services' },
  { id: 'inventory', label: 'المنتجات والمخزون', labelFr: 'Produits & Stocks', labelEn: 'Products & Inventory' },
  { id: 'crm', label: 'العملاء والديون', labelFr: 'Clients & Dettes', labelEn: 'Customers & Debts' },
  { id: 'purchases', label: 'الموردون والمشتريات', labelFr: 'Fournisseurs & Achats', labelEn: 'Suppliers & Purchases' },
  { id: 'finance', label: 'المالية', labelFr: 'Finances', labelEn: 'Finance' },
  { id: 'reports', label: 'التقارير', labelFr: 'Rapports', labelEn: 'Reports' },
  { id: 'system', label: 'النظام', labelFr: 'Système', labelEn: 'System' },
] as const;

export const NAVIGATION_ITEMS: NavigationItem[] = [
  // 1. Dashboard
  {
    id: 'dashboard',
    title: 'لوحة التحكم',
    titleEn: 'Dashboard',
    titleFr: 'Tableau de bord',
    category: 'core',
    icon: 'LayoutDashboard',
    description: 'نظرة عامة على مؤشرات المحل، الصندوق، وحالة النظام',
    descriptionFr: "Vue d'ensemble des indicateurs, de la caisse et du système",
    descriptionEn: 'Overview of store indicators, cash drawer, and system status',
  },
  // 2. POS
  {
    id: 'pos',
    title: 'نقطة البيع (POS)',
    titleEn: 'Point of Sale',
    titleFr: 'Point de Vente (POS)',
    category: 'operations',
    icon: 'ShoppingCart',
    badge: 'سريع',
    badgeColor: 'emerald',
    description: 'واجهة البيع السريع للهواتف والإكسسوارات مع دعم الباركود وقارئ IMEI',
    descriptionFr: 'Vente rapide téléphones et accessoires avec support code-barres et IMEI',
    descriptionEn: 'Fast checkout for phones and accessories with barcode and IMEI support',
  },
  // 3. Sales
  {
    id: 'sales',
    title: 'المبيعات والفواتير',
    titleEn: 'Sales & Invoices',
    titleFr: 'Ventes & Factures',
    category: 'operations',
    icon: 'Receipt',
    description: 'سجل الفواتير الصادرة، المرتجعات، وإيصالات الدفع والضمان',
    descriptionFr: 'Historique des factures émises, retours et garanties',
    descriptionEn: 'Issued invoices, returns, receipts, and warranty slips',
  },
  // 4. Digital Services
  {
    id: 'digital-services',
    title: 'الخدمات الرقمية',
    titleEn: 'Digital Services & Flexy',
    titleFr: 'Services Digitaux & Flexy',
    category: 'operations',
    icon: 'Zap',
    badge: 'فليكسي',
    badgeColor: 'emerald',
    description: 'شحن رصيد فليكسي (موبيليس، جيزي، أوريدو)، بطاقات جوجل بلاي وشحن الألعاب',
    descriptionFr: 'Recharge Flexy (Mobilis, Djezzy, Ooredoo) et cartes cadeaux',
    descriptionEn: 'Flexy recharge (Mobilis, Djezzy, Ooredoo) and digital cards',
  },
  // 5. Products & Accessories
  {
    id: 'products',
    title: 'المنتجات والإكسسوارات',
    titleEn: 'Products & Accessories',
    titleFr: 'Produits & Accessoires',
    category: 'inventory',
    icon: 'Package',
    description: 'دليل المنتجات، كابلات، شواحن، شاشات، كفرات وبطاقات الذاكرة',
    descriptionFr: 'Catalogue des produits, câbles, chargeurs et coques',
    descriptionEn: 'Product catalog, cables, chargers, screens, and cases',
  },
  // 6. Inventory
  {
    id: 'inventory',
    title: 'المخزون والجرد',
    titleEn: 'Inventory Management',
    titleFr: 'Gestion du Stock',
    category: 'inventory',
    icon: 'Boxes',
    description: 'إدارة الكميات، حركات المخزون، تنبيهات انخفاض المخزون وجرد الفروع',
    descriptionFr: 'Gestion des quantités, alertes de rupture et inventaire',
    descriptionEn: 'Quantity tracking, stock movements, and low stock alerts',
  },
  // 7. Phones & IMEI
  {
    id: 'phones-imei',
    title: 'الهواتف وأرقام IMEI',
    titleEn: 'Phones & IMEI Tracking',
    titleFr: 'Téléphones & Suivi IMEI',
    category: 'inventory',
    icon: 'Smartphone',
    badge: 'سجل IMEI',
    badgeColor: 'blue',
    description: 'تتبع الهواتف الذكية بالرقم التسلسلي وحالة الجهاز (جديد / مستعمل) والضمان',
    descriptionFr: 'Suivi des smartphones par numéro IMEI et statut de garantie',
    descriptionEn: 'Smartphone serial IMEI tracking and warranty condition',
  },
  // 8. Customers
  {
    id: 'customers',
    title: 'العملاء',
    titleEn: 'Customers',
    titleFr: 'Clients',
    category: 'crm',
    icon: 'Users',
    description: 'قاعدة بيانات العملاء، أرقام الهواتف، ولايات الإقامة ونقاط الولاء',
    descriptionFr: 'Fichier clients, numéros de téléphone et wilayas',
    descriptionEn: 'Customer database, phone numbers, and loyalty points',
  },
  // 9. Installments & Debts
  {
    id: 'installments-debts',
    title: 'الأقساط والديون',
    titleEn: 'Installments & Debts',
    titleFr: 'Facilités & Dettes',
    category: 'crm',
    icon: 'CalendarClock',
    badge: 'كريدي',
    badgeColor: 'amber',
    description: 'إدارة البيع بالتقسيط، جدول الدفعات الشهرية، والديون المستحقة للمحل',
    descriptionFr: 'Gestion des facilités de paiement et échéances de dettes',
    descriptionEn: 'Installment sales management and credit receivable balances',
  },
  // 10. Suppliers
  {
    id: 'suppliers',
    title: 'الموردون',
    titleEn: 'Suppliers',
    titleFr: 'Fournisseurs',
    category: 'purchases',
    icon: 'Truck',
    description: 'سجل تجار الجملة وموردي الهواتف وقطع الغيار في الجزائر',
    descriptionFr: 'Répertoire des grossistes et fournisseurs en Algérie',
    descriptionEn: 'Directory of wholesalers and parts suppliers in Algeria',
  },
  // 11. Purchases
  {
    id: 'purchases',
    title: 'المشتريات',
    titleEn: 'Purchases',
    titleFr: 'Achats & Commandes',
    category: 'purchases',
    icon: 'ShoppingBag',
    description: 'فواتير الشراء، طلبيات التوريد وحسابات الموردين المؤجلة',
    descriptionFr: 'Factures d’achat, commandes et dettes fournisseurs',
    descriptionEn: 'Purchase bills, supplier orders, and payables',
  },
  // 12. Cashbox
  {
    id: 'cashbox',
    title: 'الصندوق والخزينة',
    titleEn: 'Cashbox & Safe',
    titleFr: 'Caisse & Coffre',
    category: 'finance',
    icon: 'Wallet',
    badge: 'DZD',
    badgeColor: 'emerald',
    description: 'متابعة حركة السيولة النقدية، فتح وإغلاق الصندوق، وحسابات بريدي موب (BaridiMob)',
    descriptionFr: 'Gestion de caisse, liquidités et paiements BaridiMob',
    descriptionEn: 'Cash flow tracking, drawer balance, and BaridiMob receipts',
  },
  // 13. Expenses
  {
    id: 'expenses',
    title: 'المصاريف',
    titleEn: 'Expenses',
    titleFr: 'Dépenses',
    category: 'finance',
    icon: 'Coins',
    description: 'تسجيل المصاريف النثرية اليومية، صيانة المحل، وفواتير النقل',
    descriptionFr: 'Frais d’exploitation quotidiens, entretien et transport',
    descriptionEn: 'Daily petty expenses, maintenance, and transport',
  },
  // 14. Recurring Expenses
  {
    id: 'recurring-expenses',
    title: 'المصاريف المتكررة',
    titleEn: 'Recurring Expenses',
    titleFr: 'Charges Récurrentes',
    category: 'finance',
    icon: 'Repeat',
    description: 'إيجار المحل، اشتراك الإنترنت (اتصالات الجزائر)، والكهرباء والغاز',
    descriptionFr: 'Loyer, internet (Algérie Télécom) et électricité',
    descriptionEn: 'Rent, internet subscription, and electricity bills',
  },
  // 15. Employees
  {
    id: 'employees',
    title: 'الموظفون',
    titleEn: 'Employees',
    titleFr: 'Employés',
    category: 'finance',
    icon: 'UserCheck',
    description: 'إدارة البائعين والفنيين، بيانات الاتصال، وأيام العمل والحضور',
    descriptionFr: 'Gestion de l’équipe de vente et des techniciens',
    descriptionEn: 'Sales clerks and technician staff records',
  },
  // 16. Payroll
  {
    id: 'payroll',
    title: 'الرواتب',
    titleEn: 'Payroll',
    titleFr: 'Salaires & Paie',
    category: 'finance',
    icon: 'Banknote',
    description: 'حساب المرتبات الشهرية، مكافآت مبيعات الهواتف، والخصومات',
    descriptionFr: 'Calcul des salaires mensuels, primes et déductions',
    descriptionEn: 'Monthly salaries, phone sales commissions, and deductions',
  },
  // 17. Reports & Analytics
  {
    id: 'reports',
    title: 'التقارير والإحصائيات',
    titleEn: 'Reports & Analytics',
    titleFr: 'Rapports & Stats',
    category: 'reports',
    icon: 'BarChart3',
    description: 'تقارير أرباح المحل، حركة المنتجات الأكثر طلباً، ومؤشرات الأداء',
    descriptionFr: 'Rapports de rentabilité, meilleures ventes et statistiques',
    descriptionEn: 'Store profit reports, top products, and performance KPIs',
  },
  // 18. Notifications
  {
    id: 'notifications',
    title: 'الإشعارات',
    titleEn: 'Notifications',
    titleFr: 'Notifications',
    category: 'system',
    icon: 'Bell',
    description: 'تنبيهات انتهاء المخزون، مواعيد سداد الديون، وملاحظات النظام',
    descriptionFr: 'Alertes rupture de stock, dettes et messages système',
    descriptionEn: 'Stock shortage warnings, debt reminders, and notices',
  },
  // 19. Users & Permissions
  {
    id: 'users-permissions',
    title: 'المستخدمون والصلاحيات',
    titleEn: 'Users & Roles',
    titleFr: 'Utilisateurs & Rôles',
    category: 'system',
    icon: 'ShieldCheck',
    description: 'إدارة حسابات الكاشير ومدير المحل وتحديد صلاحيات التعديل والخصم',
    descriptionFr: 'Gestion des rôles, caissiers et accès administrateur',
    descriptionEn: 'Manage cashier and manager roles and access rights',
  },
  // 20. Audit Logs
  {
    id: 'audit-logs',
    title: 'سجل العمليات',
    titleEn: 'Audit Logs',
    titleFr: 'Journal d’Audit',
    category: 'system',
    icon: 'History',
    description: 'توثيق كافة العمليات، حذف الفواتير، فتح الخزينة، وتعديل أسعار الأجهزة',
    descriptionFr: 'Historique complet des opérations et suppressions',
    descriptionEn: 'Full activity log of transactions, deletions, and adjustments',
  },
  // 21. Settings
  {
    id: 'settings',
    title: 'الإعدادات',
    titleEn: 'Settings',
    titleFr: 'Paramètres',
    category: 'system',
    icon: 'Settings',
    description: 'معلومات المحل، السجل التجاري، طابعة الإيصالات الحرارية، وشروط الفاتورة',
    descriptionFr: 'Informations du magasin, registre de commerce et reçu',
    descriptionEn: 'Store details, trade register, receipt printer, and policies',
  },
];

export const ICON_MAP: Record<string, any> = {
  LayoutDashboard,
  ShoppingCart,
  Receipt,
  Package,
  Boxes,
  Smartphone,
  Users,
  CalendarClock,
  Truck,
  ShoppingBag,
  Wallet,
  Coins,
  Repeat,
  UserCheck,
  Banknote,
  Zap,
  BarChart3,
  Bell,
  ShieldCheck,
  History,
  Settings,
};
